#:schema https://mise.jdx.dev/schema/mise.json

[tools]  # tombi: format.rules.table-keys-order = "ascending"
# tools to use on all my projects
action-validator = "latest"
actionlint = "latest"
editorconfig-checker = "3.8.0"
ghalint = "latest"
pinact = "latest"
"pipx:gh-action-pulse" = { version = "latest", uvx = true }
prek = "0.4.10"
rumdl = "0.2.36"
shellcheck = "latest"
shfmt = "latest"
tombi = "1.2.4"
uv = "latest"
yamlfmt = "latest"
yamllint = "latest"
zizmor = "latest"

# To checks links
lychee = "0.24.2"
