---
fail_fast: false
repos:
  - repo: builtin
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-symlinks
      - id: detect-private-key
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: check-yaml
  - repo: local
    hooks:
      - id: actionlint
        name: actionlint
        entry: actionlint
        language: system
        files: '\.github/workflows/.*\.(yaml|yml)$'
      - id: editorconfig-checker
        name: editorconfig-checker
        entry: ec
        language: system
      - id: pinact
        name: pinact
        entry: "pinact run"
        language: system
        files: '\.github/(workflows/.*|actions/.*/action)\.(yaml|yml)$'
      - id: rumdl
        name: rumdl
        entry: "rumdl check"
        language: system
        files: '\.md$'
      - id: tombi-format
        name: "tombi format"
        entry: "tombi format"
        language: system
        files: '\.toml$'
      - id: tombi-lint
        name: "tombi lint"
        entry: "tombi lint"
        language: system
        files: '\.toml$'
      - id: zizmor
        name: zizmor
        entry: zizmor
        language: system
        files: '(\.github/(workflows/.*|actions/.*/action|dependabot\.ya?ml))|(action\.ya?ml)$'
