---
name: prek checks

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  prek-checks:
    name: Prek Checks
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: "Cleaning up"
        uses: gacts/run-and-post-run@598d7a875d5620e0457490555b5e18e46082aa47 # v1.4.4
        with:
          run: |
            echo "Pre-Check Cleanup"
            echo "~/.local" | xargs rm -rf
          post: |
            echo "Post-Check Cleanup"
            echo "~/.local" | xargs rm -rf

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up mise
        uses: jdx/mise-action@9e7f7633ff6f6d6048a9418a68d48f288f50eb14 # v4.2.3

      - name: Run prek checks
        run: prek run --all-files --show-diff-on-failure
