---
name: prek checks

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  prek-checks:
    name: Prek Checks
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: "Cleaning up"
        uses: gacts/run-and-post-run@598d7a875d5620e0457490555b5e18e46082aa47 # v1.4.4
        with:
          run: |
            echo "Pre-Check Cleanup"
            echo "~/.local" | xargs rm -rf
          post: |
            echo "Post-Check Cleanup"
            echo "~/.local" | xargs rm -rf

      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up mise
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0

      - name: Run prek checks
        run: prek run --all-files --show-diff-on-failure
